### PR TITLE
[Hacktoberfest] Use babel to generate umd version.

### PR DESCRIPTION
**Pull request by parga**
Once the changes to remove grunt get merged there will be less changes here, but the idea is to create a UMD version of the library.

Ref. https://github.com/munizart/arthemis/issues/7

### CODE REVIEW

**Comment by parga** [comment]
@PatoCinza please review

**Review by PatoCinza — APPROVED** [review]
LGTM

**Comment by munizart** [comment]
@parga  ty for your contribution :D

**Comment by PatoCinza** [comment]
This PR closes #7

**Pull request merged**
