### PR TITLE
[Hacktoberfest] Remove grunt and use npm build to run documentation and linting. 

### PR DESCRIPTION
**Pull request by parga**
PR for https://github.com/munizart/arthemis/issues/8

### CODE REVIEW

**Comment by parga** [comment]
@PatoCinza please review.

**Review by munizart — APPROVED** [review]
Thank you so much for contributing, waiting for @PatoCinza review

**Comment by parga** [comment]
@munizart still no review form @PatoCinza :/

**Review by PatoCinza — APPROVED** [review]
Sorry for the delay guys

**Comment by munizart** [comment]
Thank you all guys

**Pull request merged**
